Star Wars
LeoKuD/start-wars pull request #1
Opened 2022-01-11 15:44 UTC by LeoKuD

[Link to deploy](https://leokud.github.io/start-wars/)

2022-01-14 18:24 UTC, maximsan commented on scss/style.scss
> +  color: #072227;
why don't you use variables ? :)

2022-01-14 18:24 UTC, maximsan commented on scss/style.scss
> +  border: 2px solid #072227;
why don't you use variables ? :)

2022-01-14 18:26 UTC, maximsan commented on js/library.js
> +const MENUSTYLING = {
rename you constants according to what we discussed

2022-01-14 18:26 UTC, maximsan commented on js/library.js
> +const STYLINGPAGINATION = {
rename you constants according to what we discussed

2022-01-14 18:28 UTC, maximsan commented on js/api.js
> +    .catch((e) => alert('SERVER NOT FOUND'));
don't forget to remove you loader if you get an error too

2022-01-14 18:29 UTC, maximsan commented on js/api.js
> +  fetch(baseURL + path)
let's us string interpolation

2022-01-14 18:32 UTC, maximsan commented on js/index.js
> +        item[0].toLocaleUpperCase() + item.slice(1)
create a method for this and use the method `charAt()` to get element by index in string

2022-01-14 18:33 UTC, maximsan commented on js/index.js
> +function fillHtm(data) {
`fillHtml` ?

2022-01-14 18:40 UTC, maximsan commented on js/index.js
> +              item === 1 ? 'pagination__item_active' : ''
looks like you can use `STYLINGPAGINATION.paginationItemActive`

2022-01-14 18:42 UTC, maximsan commented on js/index.js
> +        (searchMode ? `/?search=${input.value}&page=` : '/?page=') +
create a method to construct search by page part of url based on different params

2022-01-14 18:43 UTC, maximsan commented on js/index.js
> +    getData(currentCategory + '/' + `?search=${input.value}`, (data) => {
Here use the method I advised you to create before

2022-01-14 18:46 UTC, maximsan commented on js/library.js
> +const CARDSTYLING = {
use `CLASS` or `CLASS_NAME` part in names like this, because it's more semantically clear

2022-01-14 18:52 UTC, maximsan commented on index.html
> +    <script src="./js/library.js"></script>
It's `constants.js`. You keep constants there and name should explain it.

2022-01-15 22:55 UTC, LeoKuD commented on scss/style.scss
> +    flex-basis: 200px;
Fixed. Now only rem.

2022-01-15 22:55 UTC, LeoKuD commented on scss/style.scss
> +    height: 26px;
Fixed

2022-01-15 22:57 UTC, LeoKuD commented on scss/style.scss
> +  color: #072227;
```suggestion
    color: $font-color-primary;
```

2022-01-15 22:57 UTC, LeoKuD commented on scss/style.scss
> +  border: 2px solid #072227;
Fixed

2022-01-16 11:36 UTC, LeoKuD commented on js/api.js
> +  fetch(baseURL + path)
```suggestion
  fetch(`${baseURL}/${path}`)
```

2022-01-16 11:37 UTC, LeoKuD commented on js/api.js
> +    .catch((e) => alert('SERVER NOT FOUND'));
```suggestion
          alert('SERVER NOT FOUND');
      loader.classList.remove(STYLINGLOADER.loaderVisible);
```

2022-01-16 12:01 UTC, LeoKuD commented on js/library.js
> +const MENUSTYLING = {
```suggestion
const LEFT_MENU_CLASS_NAME = {
```
Renamed all constants

2022-01-16 12:01 UTC, LeoKuD commented on js/library.js
> +const STYLINGPAGINATION = {
```suggestion
const PAGINATION_CLASS_NAME = {
```

2022-01-16 12:20 UTC, LeoKuD commented on js/index.js
> +        item[0].toLocaleUpperCase() + item.slice(1)
```suggestion
        item.charAt(0).toUpperCase() + item.slice(1)
```

2022-01-16 12:24 UTC, LeoKuD commented on js/index.js
> +function fillHtm(data) {
Yes, but it will better `fillCards`

2022-01-16 12:25 UTC, LeoKuD commented on js/index.js
> +function fillHtm(data) {
```suggestion
function fillCards(data) {
```

2022-01-16 12:25 UTC, LeoKuD commented on js/index.js
> +      cardsWrapper.append(createCard(element, index + 1));
```suggestion
      cardsWrapper.append(createCard(element, index++));
```

2022-01-16 12:37 UTC, LeoKuD commented on js/index.js
> +    .replace(/\//g, '');
This code is no longer needed.

2022-01-16 12:37 UTC, LeoKuD commented on js/index.js
> +    .slice(item.url.lastIndexOf('/', item.url.length - 2))
Deleted this code

2022-01-16 12:45 UTC, LeoKuD commented on js/index.js
> +        : `<p>${findKey(currentCategory)[key]} : ${item[key]}</p>`;
```suggestion
          const cardContent = selectedCategoryKeysArray.map((key, index) => {
    let name = findKey(currentCategory)[key];
    return index === 0
      ? `<div class='card__title'><h3 class='card__title-text'>${name} : ${item[key]}</h3><div class='card__drop-down'></div></div>`
      : `<p>${name} : ${item[key]}</p>`;
  });
```

2022-01-16 12:50 UTC, LeoKuD commented on js/index.js
> +  const countPages = Math.ceil(data.count / 10);
```suggestion
    const countPages = Math.ceil(data.count / numberElementsOnPage);
```

2022-01-16 14:08 UTC, LeoKuD commented on js/index.js
> +            }' >${item}</li>`
```
      const navContent = paginationArray.map(
        (item) =>
          `<li data-index='${item}' class='${
            PAGINATION_CLASS_NAME.paginationItem
          } ${
            (item === currentPage && !searchMode)
              ? PAGINATION_CLASS_NAME.paginationItemActive
              : (item === 1 && searchMode ? PAGINATION_CLASS_NAME.paginationItemActive : '')
          }'>${item}</li>`
      );
```

2022-01-16 14:13 UTC, LeoKuD commented on js/index.js
> +              item === 1 ? 'pagination__item_active' : ''
```suggestion
(item === 1 && searchMode ? PAGINATION_CLASS_NAME.paginationItemActive : '')
```

2022-01-16 14:15 UTC, LeoKuD commented on js/library.js
> +const CARDSTYLING = {
Fixed. Renemed all constants

2022-01-16 14:16 UTC, LeoKuD commented on index.html
> +    <script src="./js/library.js"></script>
Fixed

2022-01-16 14:22 UTC, LeoKuD commented on index.html
> +            <input id="menu__toggle" type="checkbox" />
```suggestion
            <input id="menu-toggle" type="checkbox" />
```

2022-01-16 17:16 UTC, LeoKuD commented on js/index.js
> +        (searchMode ? `/?search=${input.value}&page=` : '/?page=') +
```
function setUrl(category, search='', page='') {
  return `${category}${search && `/?search=${search}`}${page && `/?page=${page}`}`
}
```

2022-01-16 17:17 UTC, LeoKuD commented on js/index.js
> +    getData(currentCategory + '/' + `?search=${input.value}`, (data) => {
```
  if (input.value) {
    searchMode = true;
    getData(setUrl(currentCategory, input.value), (data) => {
      fillCards(data.results);
```

2022-01-18 07:14 UTC, Dev1LtJ requested changes
Hello! I left some comments. Please, fix them and let me know.

2022-01-18 07:14 UTC, Dev1LtJ commented on js/index.js
> +              : ''
Do not use nested `?`

2022-01-18 07:14 UTC, Dev1LtJ commented on js/index.js
> +  const selectedCategoryKeysArray = Object.keys(findKey(currentCategory));
create modules (import findkey and other helpers & constants)

2022-01-18 07:14 UTC, Dev1LtJ commented on js/index.js
> +    !searchMode && (currentPage = parseInt(page));
Try not to use comparisons and assignment in one expression (it's hard to read)

2022-01-18 07:14 UTC, Dev1LtJ commented on js/helpers.js
> +}
Seems like you can simplify it.

2022-01-18 07:47 UTC, LeoKuD commented on js/index.js
> +              : ''
```suggestion
      const navContent = paginationArray.map(
        (item) =>
          `<li data-index='${item}' class='${
            PAGINATION_CLASS_NAME.paginationItem
          } ${
            setActivePaginationItem(item)
          }'>${item}</li>`
      );
```

```
function setActivePaginationItem(item) {
  if (item === 1 && searchMode) {
    return PAGINATION_CLASS_NAME.paginationItemActive
  }
  else if (item === currentPage && !searchMode) {
    return PAGINATION_CLASS_NAME.paginationItemActive
  }
}
```

2022-01-18 07:56 UTC, LeoKuD commented on js/index.js
> +    !searchMode && (currentPage = parseInt(page));
```suggestion
    currentPage = searchMode ? currentPage : parseInt(page);
```

2022-01-18 08:55 UTC, LeoKuD commented on js/helpers.js
> +}
```suggestion
return CATEGORIESKEYS[category]
}
```

2022-01-18 11:27 UTC, LeoKuD commented on js/index.js
> +  const selectedCategoryKeysArray = Object.keys(findKey(currentCategory));
Done

2022-01-18 17:27 UTC, maximsan requested changes
I left comments. Please fix. Good work!

2022-01-18 17:27 UTC, maximsan commented on js/constants.js
> +  paginationHide: 'pagination_hide',
remove `pagination` part

2022-01-18 17:27 UTC, maximsan commented on js/constants.js
> +  leftMenuText: 'left-menu__text',
remove `left` part

2022-01-18 17:27 UTC, maximsan commented on js/constants.js
> +  loaderVisible: 'loader_visible',
remove `loader` part

2022-01-18 17:27 UTC, maximsan commented on js/constants.js
> +  cardShowInfo: 'card_show-info',
remove `card` part

2022-01-18 17:27 UTC, maximsan commented on js/api.js
> +      return res.json();
`() => res.json()`

2022-01-18 17:27 UTC, maximsan commented on js/api.js
> +import { cardsWrapper } from './index.js';
add indentation between  imports and initialisation parts

2022-01-18 17:27 UTC, maximsan commented on js/index.js
> +  );
method createCardContent(...

2022-01-18 17:27 UTC, maximsan commented on js/index.js
> +  const selectedCategoryNamesArray = Object.values(findKey(currentCategory));
const [keys, names] = Object.entries(findKey(currentCategory))

2022-01-18 17:27 UTC, maximsan commented on js/index.js
> +      );
const navContent = pageNumbers.map(createPageItem);

2022-01-18 17:27 UTC, maximsan commented on js/index.js
> +    currentPage = searchMode ? currentPage : parseInt(page);
currentPage = getCurrentPage();

function getCurrentPage(currentPage = 1) {
    ....
}

2022-01-19 12:49 UTC, LeoKuD commented on js/constants.js
> +  paginationHide: 'pagination_hide',
```suggestion
  export const PAGINATION_CLASS_NAME = {
  item: 'pagination__item',
  activeItem: 'pagination__item_active',
  hide: 'pagination_hide',
};
```

2022-01-19 12:49 UTC, LeoKuD commented on js/constants.js
> +  leftMenuText: 'left-menu__text',
```suggestion
export const LEFT_MENU_CLASS_NAME = {
  activeItem: 'left-menu__item_active',
  item: 'left-menu__item',
  text: 'left-menu__text',
};
```

2022-01-19 12:50 UTC, LeoKuD commented on js/constants.js
> +  loaderVisible: 'loader_visible',
```suggestion
export const LOADER_CLASS_NAME = {
  visible: 'loader_visible',
};
```

2022-01-19 12:50 UTC, LeoKuD commented on js/constants.js
> +  cardShowInfo: 'card_show-info',
```suggestion
export const CARD_CLASS_NAME = {
  card: 'card',
  showInfo: 'card_show-info',
  error: 'cards-wrapper_error',
};
```

2022-01-19 12:51 UTC, LeoKuD commented on js/api.js
> +      return res.json();
```suggestion
    .then((res) => res.json())
```

2022-01-19 12:51 UTC, LeoKuD commented on js/helpers.js
> +    item.charAt(0).toUpperCase() + item.slice(1)
```suggestion
function setCategoryName(item) {
  return `<li class="left-menu__item" data-category='${item}'><h2 class="left-menu__text">${
    item.charAt(0).toUpperCase() + item.slice(1)
  }</h2></li>`;
  
}
```

2022-01-19 12:52 UTC, LeoKuD commented on js/helpers.js
> +    item.charAt(0).toUpperCase() + item.slice(1)
```suggestion
  return setCategoryName(item)
```

2022-01-19 12:53 UTC, LeoKuD commented on js/api.js
> +import { cardsWrapper } from './index.js';
```suggestion
import { cardsWrapper } from './index.js';

```

2022-01-19 14:00 UTC, LeoKuD commented on js/index.js
> +  );
```
export function createCardContent(item) {
  const selectedCategoryKeysArray = Object.keys(findKey(currentCategory));
  const selectedCategoryNamesArray = Object.values(findKey(currentCategory));
  const cardContent = selectedCategoryKeysArray.map((key, index) => {
    let name = selectedCategoryNamesArray[index];
    return index === 0
      ? `<div class='card__title'><h3 class='card__title-text'>${name} : ${item[key]}</h3><div class='card__drop-down'></div></div>`
      : `<p>${name} : ${item[key]}</p>`;
  });
  cardContent.push(
    `<p> <a target='_blank' href='${item.url}'>more info...</> </p>`
  );
  return cardContent.join('')
}
```

2022-01-19 14:17 UTC, LeoKuD commented on js/index.js
> +  const selectedCategoryNamesArray = Object.values(findKey(currentCategory));
In my case it doesn't work.

2022-01-19 14:19 UTC, LeoKuD commented on js/index.js
> +    const paginationArray = [];
Done.

2022-01-19 14:23 UTC, LeoKuD commented on js/index.js
> +      );
```suggestion
      const navContent = pageNumbers.map(item => createPageItem(item));
```

2022-01-19 14:39 UTC, LeoKuD commented on js/index.js
> +  elem && elem.classList.toggle(CARD_CLASS_NAME.cardShowInfo);
```suggestion
  e.target.closest(ATTRIBUTES_NAME.dataIndexasAtr)?.classList.toggle(CARD_CLASS_NAME.showInfo);
```

2022-01-19 14:44 UTC, LeoKuD commented on js/index.js
> +    currentPage = searchMode ? currentPage : parseInt(page);
```suggestion
    currentPage = getCurrntPage(currentPage, searchMode, page);
```

2022-01-19 14:56 UTC, LeoKuD commented
Pagination block goes down under cards when adaptiv. Added search button.

2022-01-19 16:24 UTC, maximsan commented on js/index.js
> +  const selectedCategoryNamesArray = Object.values(findKey(currentCategory));
why ? from your code I see it should work

2022-01-19 16:38 UTC, maximsan approved these changes
Looks fine for me. Good work! Approved!

2022-01-19 20:40 UTC, Mrio1 approved these changes

2022-01-19 20:40 UTC, Mrio1 commented on js/index.js
> +    items.forEach((elem) =>
Use ```const``` for ```items```.

2022-01-20 17:37 UTC, LeoKuD commented on js/index.js
> +    items.forEach((elem) =>
Ok, thanks. Fixed.

2022-01-20 17:42 UTC, merged